const Label = {
  AND: "AND",
  AVAILABLE: "available",
  AVERAGE_OPEN_PRICE: "averageOpenPrice",
  BASE_COIN: "baseCoin",
  BASE_VOLUME: "baseVolume",
  BUY: "buy",
  CHECK_BAR_SERIES: "CHECK BAR SERIES",
  CLIENT_OID: "clientOid",
  CLOSE: "close",
  COIN: "coin",
  CTIME: "ctime",
  COIN_NAME: "coinName",
  DEV: "dev",
  DMCBL: "dmcbl",
  END: "End=",
  END_TIME: "endTime",
  ENTRY: "Entry ",
  ENTRY_PRICE: "entryPrice",
  ENTRY_WITH_EMOJI: "➡️ Entry ",
  EXIT: "Exit ",
  EXIT_WITH_EMOJI: "⬅️ Exit ",
  FEE_DETAIL: "feeDetail",
  FIXED_MAX_AVAILABLE: "fixedMaxAvailable",
  FOR_PRICE: " for price ",
  FORCE: "force",
  FUTURE: "futures",
  GRANULARITY: "granularity",
  HOLD_SIDE: "holdSide",
  INSUFFICIENT: "Insufficient",
  IS_PLAN: "isPlan",
  LAST_PR: "lastPr",
  LEVERAGE: "leverage",
  LIMIT: "limit",
  LONG: "Long",
  LONG_WITH_EMOJI: "⤴️ Long ",
  MARGIN: "margin",
  MARGIN_COIN: "marginCoin",
  MARGIN_MODE: "marginMode",
  MARGIN_SIZE: "marginSize",
  MARK_PRICE: "markPrice",
  MARKET: "market",
  MIN_OPEN_COUNT: "minOpenCount",
  MIN_TRADE_NUM: "minTradeNum",
  MIN_TRADE_USDT: "minTradeUSDT",
  OPEN: "open",
  OPEN_LEVERAGE: "openLeverage",
  OPEN_LONG: "open_long",
  OPEN_PRICE_AVG: "openPriceAvg",
  OPEN_SHORT: "open_short",
  OPEN_SIZE: "openSize",
  OR: " Or ",
  ORDER_LIST: "orderList",
  ORDER_SOURCE: "orderSource",
  ORDER_TYPE: "orderType",
  PLAN_TYPE: "planType",
  POS_SIDE: "posSide",
  PRICE: "price",
  PRICE_AVG: "priceAvg",
  PROD: "prod",
  PRODUCT_TYPE: "productType",
  PROFIT: "Profit",
  QUOTE_VOLUME: "quoteVolume",
  RANGE_RATE: "rangeRate",
  ROE: "roe",
  S: "S",
  SELL: "sell",
  SHORT: "Short",
  SHORT_WITH_EMOJI: "⤵️ Short ",
  SIDE: "side",
  SIGN: "RFIut#",
  SIM: "simulation",
  SIZE: "size",
  SPBL: "spbl",
  SPOT: "spot",
  STAT: "STAT",
  START: "Start=",
  START_TIME: "startTime",
  STOP_LOSS: "Stop loss",
  SUFFICIENT: "Sufficient",
  SYMBOL: "symbol",
  SYMBOL_S_PRICE_S: "Symbol=%s Price=%s",
  TIME_IN_FORCE_VALUE: "timeInForceValue",
  TOTAL: "total",
  TOTAL_PROFITS: "totalProfits",
  TRACKING_LIST: "trackingList",
  TRACKING_NO: "trackingNo",
  TRADE_SIDE: "tradeSide",
  TRIGGER_PRICE: "triggerPrice",
  UMCBL: "umcbl",
  UNREALIZED_PL: "unrealizedPL",
  USDT: "usdt",
  USDT_FUTURES: "usdt-futures",
  USDT_SPBL: "usdt_spbl",
  UTIME: "utime",
};

export { Label };
