/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  CandlestickIntervalEnum,
  IndicatorType,
  InvestorType,
  MixHoldSideEnum,
  MixMarginModeEnum,
  Profile,
} from "../common/MapperType";
import {
  QuickExitFilter,
  StandardFilter,
  StandardFilterWithoutNotFar,
  StandardFilterWithoutRoi,
  DevFilter,
} from "../filter/Filter";

// NOTE: Présets extraits de l'ancienne grosse classe InvestorFactory pour alléger le bundle.
// Ils gardent exactement les mêmes valeurs qu'avant pour compatibilité.
export const PRESETS: Record<
  InvestorType,
  {
    strategies: { type: IndicatorType; params?: number[] }[];
    filters: any[];
    period: CandlestickIntervalEnum;
    position: MixHoldSideEnum | null;
    leverage: number;
    marginMode: MixMarginModeEnum;
    exit: boolean | null;
    activeLimit: boolean;
    profiles: Profile[];
    riskRange?: [number, number];
  }
> = {
  conservative: {
    strategies: [{ type: "MACD" }, { type: "ENV" }],
    filters: [new StandardFilterWithoutRoi()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 3,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0, 0.2],
  },
  moderate: {
    strategies: [{ type: "OR_MACD_ENV" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 5,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.2, 0.5],
  },
  balanced: {
    strategies: [{ type: "OR_MACD_ENV" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 5,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.25, 0.55],
  },
  aggressive: {
    strategies: [{ type: "DOUBLE_AVG" }, { type: "TRIPLE_AVG" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 10,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.5, 0.8],
  },
  momentum: {
    strategies: [{ type: "DOUBLE_AVG" }],
    filters: [new StandardFilterWithoutNotFar()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 7,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.45, 0.75],
  },
  contrarian: {
    strategies: [{ type: "ENV" }],
    filters: [new StandardFilterWithoutRoi()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 5,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.35, 0.6],
  },
  trend_sniper: {
    strategies: [{ type: "TRIPLE_AVG" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 8,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.55, 0.8],
  },
  stable_seeker: {
    strategies: [{ type: "MACD" }],
    filters: [new StandardFilterWithoutNotFar()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 3,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.15, 0.35],
  },
  degen: {
    strategies: [{ type: "ADAPTIVE" }],
    filters: [new DevFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 15,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.8, 1],
  },
  microcap: {
    strategies: [{ type: "ADAPTIVE_WITH_TRAILING" }],
    filters: [new QuickExitFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 5,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.7, 0.95],
  },
  sentiment: {
    strategies: [{ type: "OR_MACD_ENV" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 5,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.4, 0.65],
  },
  ath_rebound: {
    strategies: [{ type: "TRIPLE_AVG" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 6,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.45, 0.7],
  },
  macd_master: {
    strategies: [{ type: "MACD" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 10,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.55, 0.85],
  },
  envelope_strategist: {
    strategies: [{ type: "ENV" }],
    filters: [new StandardFilterWithoutNotFar()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 7,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.4, 0.65],
  },
  active_trader: {
    strategies: [{ type: "DOUBLE_AVG" }, { type: "TRIPLE_AVG" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.FIFTEEN_MINUTES,
    position: null,
    leverage: 12,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.5, 0.8],
  },
  speculative_gem: {
    strategies: [{ type: "ADAPTIVE_WITH_TRAILING" }, { type: "ADAPTIVE" }],
    filters: [new QuickExitFilter()],
    period: CandlestickIntervalEnum.HALF_HOURLY,
    position: null,
    leverage: 10,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.8, 1],
  },
  institutional: {
    strategies: [{ type: "MACD" }, { type: "ENV" }],
    filters: [new StandardFilterWithoutRoi()],
    period: CandlestickIntervalEnum.FOUR_HOURLY,
    position: null,
    leverage: 3,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.15, 0.4],
  },
  defi: {
    strategies: [{ type: "ADAPTIVE" }, { type: "ENV" }],
    filters: [new StandardFilter()],
    period: CandlestickIntervalEnum.HOURLY,
    position: null,
    leverage: 6,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.4, 0.7],
  },
  sustainable: {
    strategies: [{ type: "MACD" }, { type: "ENV" }],
    filters: [new StandardFilterWithoutNotFar()],
    period: CandlestickIntervalEnum.FOUR_HOURLY,
    position: null,
    leverage: 2,
    marginMode: MixMarginModeEnum.CROSSED,
    exit: null,
    activeLimit: false,
    profiles: [Profile.FUTURE, Profile.DEV],
    riskRange: [0.1, 0.35],
  },
};
